version: '3.9'
services:
  reports:
    build: 
      context: ./
    image: kami-pricing:0.2.0
    container_name : "kami-pricing"
    hostname: "kami-pricing"
    volumes:
      - ./logs:/app/logs
      - ./credentials:/app/credentials
    restart: always
