name: Deploy Kami Pricing to Docker Hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Generate Requirements File
        run: |
          pip install poetry
          poetry export -f requirements.txt --output requirements.txt --without-hashes --without dev --without doc
        working-directory: .

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install toml
        working-directory: .
      
      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          echo "APP_VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            devkamico/kami-pricing:latest
            devkamico/kami-pricing:${{ env.APP_VERSION }}
          build-args: |
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_PASS=${{ secrets.EMAIL_PASS }}
            BOTCONVERSA_API_KEY=${{ secrets.BOTCONVERSA_API_KEY }}
